############################################################
## Edited from script generated by Vivado HLS.
############################################################
open_project -reset rdma_receiver
set_top receiveData
add_files receiveData.cpp
add_files -tb receiveData_tb.cpp
open_solution -reset "temp_solution"
set_part {xcku060-ffva1156-2-i}
create_clock -period 6.3
csim_design
csynth_design
cosim_design
export_design
exit
